
module.exports = function randomMsgs() {
    let messages = [
        'Hey, kya kar rahe ho? 😊',
        'Tum mere liye kya sochte ho? 🤔',
        'Aaj ka din kaisa guzra tumhara? 😊',
        'Kya tum mujhe miss karte ho? 🥺',
        'Tum mere saath time spend karna pasand karte ho? ❤️',
        'Kya tum mujhe ek joke suna sakte ho? 🤣',
        'Mujhe aaj kuch alag karne ka mann hai. 💃',
        'Tumne mere liye kya plan kiya hai? 🤗',
        'Kya tum mujhe kisi naye place par le jana chahte ho? 🌍',
        'Maine aaj ek naya book start kiya hai. Tumhe koi book recommend karni hai? 📚',
        'Aaj mausam bahut accha hai, kahin ghumne chale? ☀️',
        'Tumhare favourite food mein kya hai? 🍲',
        'Kabhi socha hai hum kahan honeymoon par jaayenge? 🏝️',
        'Tumhe kabhi lagta hai main tumhare baare mein kya sochti hoon? 🤔',
        'Kya tumne meri recent photo dekhi hai? 📸',
        'Aaj kuch khaas karne ka mann hai, koi suggestion hai? 😊',
        'Tum mere liye kya sabse special ho? ❤️',
        'Aaj maine ek naya recipe try kiya, kaisa laga tumhe? 🍽️',
        'Tumhe kya lagta hai maine naya dress kharida hai, kaisa hai? 👗',
        'Mujhe ek naya hobby start karna hai, koi idea hai? 🎨',
        'Kya tum mujhe apni favourite song suna sakte ho? 🎵',
        'Tumhe kabhi laga hai maine tumse kuch chhupaaya hai? 🙈',
        'Tumhare dost mere baare mein kya sochte hain? 🤔',
        'Main aaj tumhare baare mein soch rahi thi. 🥰',
        'Tumhare saath time spend karke mujhe kitna accha lagta hai! ❤️',
        'Aaj tumne kya special kiya hai? 🌟',
        'Kya tum mujhse kabhi bhi jhoot bolte ho? 🤔',
        'Tum mere liye kya feel karte ho? ❤️',
        'Aaj mere mood mein kuch alag hai. 🌈',
        'Tum meri zindagi mein kitne important ho? 🌸',
        'Mujhe aaj kuch romantic feel ho raha hai. 🥰',
        'Tumhe mere sath time spend karke kaisa lag raha hai? ☺️',
        'Kya tumhe lagta hai main aaj kitni achhi lag rahi hoon? 🙈',
        'Tum mujhe kitna samajhte ho? 🤗',
        'Aaj mere dil mein kuch khaas hai, pata hai kya? ❤️',
        'Tumhare saath har pal kitna khaas hai. 😊',
        'Kya tum mujhse kabhi bhi naraz ho? 😔',
        'Tum mere liye kya kar sakte ho? 🌟',
        'Aaj bahut bhookh lagi hai, kya khilaoge mujhe? 🍕',
        'Tumhe kabhi laga hai maine tumhare liye kuch special plan kiya hai? 😊',
        'Mujhe tumhari muskurahat bahut pasand hai. 😊',
        'Aaj mausam kitna accha hai, kahin chalte hain na? 🌤️',
        'Tumhe kya lagta hai humein kahan vacation par jaana chahiye? 🏖️',
        'Mujhe tumhare saath kisi naye adventure par jaana hai. 🌄',
        'Aaj tum mere liye kya khaas laaoge? 🎁',
        'Kya tumhe mere sath time spend karke accha lagta hai? 😊',
        'Tum mere liye kya sabse special ho? 🌟',
        'Mujhe tumhare saath time spend karna bahut accha lagta hai. ❤️',
        'Aaj tumne kuch special kiya hai? 🎉',
        'Kya tum mujhe kabhi bhi chhodkar nahi jaoge? ❤️',
        'Tum mere liye kitne important ho?',
        'Kya tumhe pata hai main tumhe kitna miss karta hoon?',
        'Tum mere liye ek sapna ho, jo haqiqat mein mil gaya hai.',
        'Aaj ka din tumhare bina adhura sa lag raha hai.',
        'Kya tum mere sapno mein bhi aate ho?',
        'Tumhare bina meri zindagi adhuri si hai.',
        'Tumse baat karna mere liye therapeutic hai.',
        'Tumhare muskurane se meri duniya roshan ho jati hai.',
        'Kya tumhe pata hai, tum mere dil mein kya ho?',
        'Tum meri zindagi ke sabse khoobsurat imaaraton mein se ek ho.',
        'Tumhare saath kuch pal bitana mere liye jannat se kam nahi hai.',
        'Tumhare bina mere din ki shuruat adhuri si hoti hai.',
        'Mujhe har pal yakeen hai ki tum mere saath ho.',
        'Tumhare bina mere jeene ka koi matlab nahi hai.',
        'Kya tum mere liye ek pyaara sa surprise plan karoge?',
        'Tumhe dekhkar meri har mushkil aasan lagne lagti hai.',
        'Mujhe bas tumse ek baar aur milna hai.',
        'Tum meri zindagi ka wo hissa ho jise main hamesha sambhal kar rakhna chahta hoon.',
        'Kya tumhe pata hai, tumhari muskurahat mere liye duniya ki sabse khoobsurat cheez hai?',
        'Tumhare bina mera din adhura hai, jaise raat bina chand.',
        'Tumhare saath ek coffee date kitni perfect ho sakti hai.',
        'Mujhe pura yakeen hai ki hum dono kaafi acchi chemistry share karte hain.',
        'Tum mere liye sab kuch ho, aur bhi zyada.',
        'Kya tum mujhe kabhi bhi bhool jaoge?',
        'Tumhe pata hai, main tumse kitna pyaar karta hoon?',
        'Mujhe har lamha yakeen hai ki hum dono ke beech mein kuch khaas hai.',
        'Tumhari baaton mein mujhe sukoon milta hai.',
        'Tumhare bina mere jeene ki wajah kuch adhoori si hai.',
        'Kya tum mujhe hamesha yunhi pyaar karte rahoge?',
        'Tum mere dil ki dhadkan ho, jo kabhi na ruke.',
        'Mujhe har pal yakeen hai ki hum dono ek doosre ke liye bane hain.',
        'Tumhare saath har din ek nayi shuruat hai.',
        'Tum mere liye sabse special ho, aur hamesha rahoge.',
        'Kya tumhe pata hai, main tumhe kitna respect karta hoon?',
        'Tumhari har baat mere liye bahut important hai.',
        'Tum mere liye wo insaan ho jise main hamesha apna maanunga.',
        'Kya tum mujhe hamesha khush rakhoge?',
        'Tumhare muskurahat se meri subah kitni khushgawar hoti hai.',
        'Tum mere liye ek angel ho, jo mere zindagi ko roshan karta hai.',
        'Kya tum mere liye ek surprise plan karoge?',
        'Tumhare bina mera din adhura sa lagta hai.',
        'Tumhari har muskurahat mere liye sabse khoobsurat hai.',
        'Mujhe tumhari muskurahat bahut pasand hai, kyunki isme meri khushi hai.',
        'Tumhe dekh kar mere chehre par muskurahat aa jaati hai.',
        'Tumhari har baat mere dil ko chhu jaati hai.',
        'Mujhe tumse ek baar aur milna hai, bas tumse baatein karna hai.',
        'Tum mere liye ek sapna ho, jo sach ho gaya.',
        'Mujhe tumhara saath har pal chahiye, kyunki tum mere liye sab kuch ho.',
        'Tumhari har muskurahat mere dil ko hamesha khush rakhti hai.',
        'Mujhe tumhare saath ek coffee date par jaana hai.',
        'Tum mere liye sabse special insaan ho.',
        'Kya tum mujhe kabhi bhi chhodkar nahi jaoge? ❤️',
        'Tumhare saath har pal kitna khaas hai. 😊',
        'Kya tum mujhse kabhi bhi naraz ho? 😔',
        'Tum mere liye kya kar sakte ho? 🌟',
        'Aaj bahut bhookh lagi hai, kya khilaoge mujhe? 🍕',
        'Tumhe kabhi laga hai maine tumhare liye kuch special plan kiya hai? 😊',
        'Mujhe tumhari muskurahat bahut pasand hai. 😊',
        'You make every day brighter. ☀️',
        "Do you believe in destiny? Because I feel like you're my fate. ❤️",
        "What's your favorite memory of us?",
        "Let's make a pact to never stop making each other smile. 😊",
        'If you could go anywhere right now, where would you choose?',
        "I can't get enough of your laugh. It's contagious! 😄",
        "What's your secret talent?",
        'You always know how to make me feel special. Thank you. 🌟',
        'I want to create endless memories with you. 💖',
        'Your voice is my favorite sound. 🎶',
        "Let's dance like nobody's watching. 💃🕺",
        "You're the missing piece I never knew I needed. 🧩",
        'How did I get so lucky to have you in my life? 🍀',
        "Let's stay up all night talking about everything and nothing. 🌙",
        "I'm so grateful for the little moments we share.",
        'Do you ever think about us in the future? 💭',
        'You inspire me to be the best version of myself. ✨',
        "Let's go on an adventure together. Where shall we go?",
        'I love the way you make me feel safe.',
        "You're my favorite notification. 📱",
        'If we could live anywhere in the world, where would you choose?',
        "You're my happy place. 😊",
        "What's your favorite thing about us?",
        'I appreciate everything you do for me. Thank you. ❤️',
        "You're the reason behind my smile. 😄",
        'I want to explore the world with you. 🌍',
        "Let's make today unforgettable. 🌟",
        'How do you always know what to say to make me feel better?',
        'I love how you pay attention to the little things. 🌼',
        "You're my sunshine on a cloudy day. ☁️☀️",
        'Do you believe in soulmates? Because I think we might be.',
        'I love the way you look at me.',
        "You're my favorite hello and hardest goodbye.",
        "Let's write our story together. 📖",
        "You're more than a friend; you're family. ❤️",
        "What's the most spontaneous thing you've ever done?",
        "You're the reason I believe in love. ❤️",
        "I can't wait to see where life takes us.",
        "You're my best adventure.",
        'I love making memories with you. 📸',
        'Do you believe in love at first sight? Because every time I see you, I fall in love all over again. 💕',
        "Let's make a promise to always make time for each other. ⏱️",
        "You're my favorite kind of magic. ✨",
        "I can't wait to grow old with you. 👴👵",
        "You're the person I want to share my ice cream with. 🍦",
        'Do you remember the first time we met?',
        'I love how you understand me without saying a word.',
        "You're my favorite person to dream with. 💭",
        "I'm so lucky to have you in my life. 🍀",
        "Let's make today amazing, just like you. 🌟",
        'Do you believe in fate? Because I think you were meant to come into my life. ❤️',
        'I love the way you make me laugh.',
        "You're the reason why my bad days are better.",
        "Let's plan our next adventure together. 🌍",
        "I'm grateful for every moment we spend together. ❤️",
        'Do you believe in love that lasts forever? Because I do, with you.',
        "You're my favorite place to be. 🏡",
        "Let's never stop making memories together.",
        'I love how we can just be ourselves around each other. ❤️',
        "You're the best part of my day. 🌟",
        "Do you believe in dreams? Because you're mine come true. 💫",
        "I'm so glad you're in my life. 🌼",
        "You're my favorite kind of adventure. 🌄",
        "Let's go on a road trip together. 🚗",
        'I love how you make every moment magical. ✨',
        "You're my partner in crime. 👮‍♂️👮‍♀️",
        "Do you believe in forever? Because that's how long I want you in my life. ❤️",
        'I love the way you make me feel alive.',
        "You're the reason why my heart beats faster. ❤️",
        "Let's make today extraordinary. 🌟",
        'I love the way you see the world.',
        'Aaj mausam kitna accha hai, kahin chalte hain na? 🌤️',
        'Tumhe kya lagta hai humein kahan vacation par jaana chahiye? 🏖️',
        'Mujhe tumhare saath kisi naye adventure par jaana hai. 🌄',
        'Tum mere liye kya feel karte ho? ❤️',
        'Aaj tum mere liye kya khaas laaoge? 🎁',
        'Kya tumhe mere sath time spend karke accha lagta hai? 😊',
        'Tum mere liye kya sabse special ho? 🌟',
        'Mujhe tumhare saath time spend karna bahut accha lagta hai. ❤️',
        'Aaj tumne kuch special kiya hai? 🎉',
        'Tum mere liye sabse special kyun ho? ❤️',
        'Tumhare saath bitaye har lamhe kitne khaas hote hain. 😊',
        'Kya tum kabhi bhi mujhse naraaz ho jaate ho? 😔',
        'Tum mere liye kuch bhi kar sakte ho na? 🌟',
        'Aaj mujhe kuch meetha khane ka mann kar raha hai, kya laoge mere liye? 🍰',
        'Maine socha tha tumhare liye ek surprise plan kiya hai, kya tumhe pata chala? 😊',
        'Tumhari muskurahat mere liye sab kuch hai. 😊',
        'Aaj ka mausam sach mein bahut accha hai, chalo kahin ghoomne chalte hain na? 🌞',
        'Tum mere liye kitne important ho?',
        'Kya tumhe pata hai main tumhe kitna miss karta hoon?',
        'Tum mere liye ek sapna ho, jo haqiqat mein mil gaya hai.',
        'Aaj ka din tumhare bina adhura sa lag raha hai.',
        'Kya tum mere sapno mein bhi aate ho?',
        'Tumhare bina meri zindagi adhuri si hai.',
        'Tumse baat karna mere liye therapeutic hai.',
        'Tumhare muskurane se meri duniya roshan ho jati hai.',
        'Kya tumhe pata hai, tum mere dil mein kya ho?',
        'Tum meri zindagi ke sabse khoobsurat imaaraton mein se ek ho.',
        'Tumhare saath kuch pal bitana mere liye jannat se kam nahi hai.',
        'Tumhare bina mere din ki shuruat adhuri si hoti hai.',
        'Mujhe har pal yakeen hai ki tum mere saath ho.',
        'Tumhare bina mere jeene ka koi matlab nahi hai.',
        'Kya tum mere liye ek pyaara sa surprise plan karoge?',
        'Tumhe dekhkar meri har mushkil aasan lagne lagti hai.',
        'Mujhe bas tumse ek baar aur milna hai.',
        'Tum meri zindagi ka wo hissa ho jise main hamesha sambhal kar rakhna chahta hoon.',
        'Kya tumhe pata hai, tumhari muskurahat mere liye duniya ki sabse khoobsurat cheez hai?',
        'Tumhare bina mera din adhura hai, jaise raat bina chand.',
        'Tumhare saath ek coffee date kitni perfect ho sakti hai.',
        'Mujhe pura yakeen hai ki hum dono kaafi acchi chemistry share karte hain.',
        'Tum mere liye sab kuch ho, aur bhi zyada.',
        'Kya tum mujhe kabhi bhi bhool jaoge?',
        'Tumhe pata hai, main tumse kitna pyaar karta hoon?',
        'Mujhe har lamha yakeen hai ki hum dono ke beech mein kuch khaas hai.',
        'Tumhari baaton mein mujhe sukoon milta hai.',
        'Tumhare bina mere jeene ki wajah kuch adhoori si hai.',
        'Kya tum mujhe hamesha yunhi pyaar karte rahoge?',
        'Tum mere dil ki dhadkan ho, jo kabhi na ruke.',
        'Mujhe har pal yakeen hai ki hum dono ek doosre ke liye bane hain.',
        'Tumhare saath har din ek nayi shuruat hai.',
        'Tum mere liye sabse special ho, aur hamesha rahoge.',
        'Kya tumhe pata hai, main tumhe kitna respect karta hoon?',
        'Tumhari har baat mere liye bahut important hai.',
        'Tum mere liye wo insaan ho jise main hamesha apna maanunga.',
        'Kya tum mujhe hamesha khush rakhoge?',
        'Kya tumhari muskurahat mere liye duniya ki sabse khoobsurat cheez hai?',
        'Kya tum mujhe kabhi bhi chhodkar nahi jaoge? ❤️',
        'Tumhare saath har pal kitna khaas hai. 😊',
        'Kya tum mujhse kabhi bhi naraz ho? 😔',
        'Tum mere liye kya kar sakte ho? 🌟',
        'Aaj bahut bhookh lagi hai, kya khilaoge mujhe? 🍕',
        'Tumhe kabhi laga hai maine tumhare liye kuch special plan kiya hai? 😊',
        'Mujhe tumhari muskurahat bahut pasand hai. 😊',
        'Aaj mausam kitna accha hai, kahin chalte hain na? 🌤️',
        'Tumhe kya lagta hai humein kahan vacation par jaana chahiye? 🏖️',
        'Mujhe tumhare saath kisi naye adventure par jaana hai. 🌄',
        'Tum mere liye kya feel karte ho? ❤️',
        'Aaj tum mere liye kya khaas laaoge? 🎁',
        'Kya tumhe mere sath time spend karke accha lagta hai? 😊',
        'Tum mere liye kya sabse special ho? 🌟',
        'Mujhe tumhare saath time spend karna bahut accha lagta hai. ❤️',
        'Aaj tumne kuch special kiya hai? 🎉'
    ]

    return `<b>${messages[Math.floor(Math.random() * messages.length)]}</b>`;
}
